### ISSUE TITLE
Crash when using regular expressions

### ISSUE THREAD

**Issue by tomascapek** [hchasestevens/bellybutton#13]
I created a simple rule from which I expected to fail on every single file in my project:

    settings:
      all_files: &all_files !settings
        included:
          - ~+/*
        excluded:
          - ~+/.tox/*
        allow_ignore: yes

    default_settings: *all_files
    
    rules:
      SimpleRule:
        description: "Simple rule"
        expr: !regex .*

And then I launched it:

    bellybutton lint

Which results in a crash:

    Traceback (most recent call last):
      File "/home/dev_intern/.virtualenvs/bellybutton-test/bin/bellybutton", line 11, in <module>
        sys.exit(main())
      File "/home/dev_intern/.virtualenvs/bellybutton-test/lib/python3.5/site-packages/bellybutton/cli.py", line 203, in main
        for arg in args.func.__code__.co_varnames[:args.func.__code__.co_argcount]
      File "/home/dev_intern/.virtualenvs/bellybutton-test/lib/python3.5/site-packages/bellybutton/cli.py", line 167, in lint
        linting_results = list(lint_file(filepath, file_contents, rules))
      File "/home/dev_intern/.virtualenvs/bellybutton-test/lib/python3.5/site-packages/bellybutton/linting.py", line 65, in lint_file
        for match in re.finditer(rule.expr)
    TypeError: finditer() missing 1 required positional argument: 'string'

Can this be fixed soon?

**Comment by hchasestevens** [comment]
Hello @tomascapek , thanks for raising this.  The bug you described should now be fixed in the latest release (v.2.2). Would you mind having a look to verify? Thanks again!

**Comment by tomascapek** [comment]
It works fine now. Thank you!
